version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bloodsky_postgres
    ports:
      - "${DB_PORT:-5437}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-blood_sky_drone}
      POSTGRES_DB: ${DB_NAME:-blood_sky}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: bloodsky_pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@bloodsky.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-blood_sky_drone}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: